name: torch-gpu
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch
  - pytorch-cuda=12.1
  - torchvision
  - torchaudio
  - numpy
  - matplotlib
  - scikit-learn
  - tqdm
  - pip
